<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Mon, 26 Feb 2024 12:40:15 +0000
 */
$conf['title'] = 'Halo Re: Claimed';
$conf['lang'] = 'en';
$conf['license'] = 'cc-by-sa';
$conf['disableactions'] = 'register';
